// <auto-generated />
using System;
using EduSense.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EduSense.DAL.Migrations
{
    [DbContext(typeof(EduSenseDbContext))]
    [Migration("20260902140755_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EduSense.DAL.Models.AnswerOptionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AnswerOption", (string)null);
                });

            modelBuilder.Entity("EduSense.DAL.Models.OrganisationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Organisation", (string)null);
                });

            modelBuilder.Entity("EduSense.DAL.Models.OrganisationUserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrganisationId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId", "UserId")
                        .IsUnique();

                    b.ToTable("OrganisationUser", (string)null);
                });

            modelBuilder.Entity("EduSense.DAL.Models.QuestionAnswerOptionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnswerOptionId")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnswerOptionId");

                    b.HasIndex("QuestionId", "AnswerOptionId")
                        .IsUnique();

                    b.ToTable("QuestionAnswerOption", (string)null);
                });

            modelBuilder.Entity("EduSense.DAL.Models.QuestionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Question", (string)null);
                });

            modelBuilder.Entity("EduSense.DAL.Models.RespondentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SurveyId")
                        .HasColumnType("integer");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TokenIsUsed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("TokenUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId");

                    b.HasIndex("Email", "Token", "SurveyId")
                        .IsUnique();

                    b.ToTable("Respondent", (string)null);
                });

            modelBuilder.Entity("EduSense.DAL.Models.ResponseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("QuestionAnswerOptionId")
                        .HasColumnType("integer");

                    b.Property<int>("RespondentId")
                        .HasColumnType("integer");

                    b.Property<int>("SurveyQuestionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuestionAnswerOptionId");

                    b.HasIndex("RespondentId");

                    b.HasIndex("SurveyQuestionId");

                    b.ToTable("Response", (string)null);
                });

            modelBuilder.Entity("EduSense.DAL.Models.SurveyModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SurveyExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.HasIndex("Title", "SurveyExpiryDate", "OrganisationId")
                        .IsUnique();

                    b.ToTable("Survey", (string)null);
                });

            modelBuilder.Entity("EduSense.DAL.Models.SurveyQuestionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<int>("SurveyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SurveyId", "QuestionId")
                        .IsUnique();

                    b.ToTable("SurveyQuestion", (string)null);
                });

            modelBuilder.Entity("EduSense.DAL.Models.OrganisationUserModel", b =>
                {
                    b.HasOne("EduSense.DAL.Models.OrganisationModel", "Organisation")
                        .WithMany("OrganisationUsers")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("EduSense.DAL.Models.QuestionAnswerOptionModel", b =>
                {
                    b.HasOne("EduSense.DAL.Models.AnswerOptionModel", "AnswerOption")
                        .WithMany("QuestionAnswerOptions")
                        .HasForeignKey("AnswerOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduSense.DAL.Models.QuestionModel", "Question")
                        .WithMany("QuestionAnswerOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnswerOption");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("EduSense.DAL.Models.RespondentModel", b =>
                {
                    b.HasOne("EduSense.DAL.Models.SurveyModel", "Survey")
                        .WithMany("Respondents")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("EduSense.DAL.Models.ResponseModel", b =>
                {
                    b.HasOne("EduSense.DAL.Models.QuestionAnswerOptionModel", "QuestionAnswerOption")
                        .WithMany("Responses")
                        .HasForeignKey("QuestionAnswerOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduSense.DAL.Models.RespondentModel", "Respondent")
                        .WithMany("Responses")
                        .HasForeignKey("RespondentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduSense.DAL.Models.SurveyQuestionModel", "SurveyQuestion")
                        .WithMany("Responses")
                        .HasForeignKey("SurveyQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionAnswerOption");

                    b.Navigation("Respondent");

                    b.Navigation("SurveyQuestion");
                });

            modelBuilder.Entity("EduSense.DAL.Models.SurveyModel", b =>
                {
                    b.HasOne("EduSense.DAL.Models.OrganisationModel", "Organisation")
                        .WithMany("Surveys")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("EduSense.DAL.Models.SurveyQuestionModel", b =>
                {
                    b.HasOne("EduSense.DAL.Models.QuestionModel", "Question")
                        .WithMany("SurveyQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduSense.DAL.Models.SurveyModel", "Survey")
                        .WithMany("SurveyQuestions")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("EduSense.DAL.Models.AnswerOptionModel", b =>
                {
                    b.Navigation("QuestionAnswerOptions");
                });

            modelBuilder.Entity("EduSense.DAL.Models.OrganisationModel", b =>
                {
                    b.Navigation("OrganisationUsers");

                    b.Navigation("Surveys");
                });

            modelBuilder.Entity("EduSense.DAL.Models.QuestionAnswerOptionModel", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("EduSense.DAL.Models.QuestionModel", b =>
                {
                    b.Navigation("QuestionAnswerOptions");

                    b.Navigation("SurveyQuestions");
                });

            modelBuilder.Entity("EduSense.DAL.Models.RespondentModel", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("EduSense.DAL.Models.SurveyModel", b =>
                {
                    b.Navigation("Respondents");

                    b.Navigation("SurveyQuestions");
                });

            modelBuilder.Entity("EduSense.DAL.Models.SurveyQuestionModel", b =>
                {
                    b.Navigation("Responses");
                });
#pragma warning restore 612, 618
        }
    }
}
