<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EduSense.BLL\EduSense.BLL.csproj" />
    <ProjectReference Include="..\EduSense.Shared\EduSense.Shared.csproj" />
  </ItemGroup>

</Project>
