<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>fe86fd6d-251d-4203-b655-ff3ba7e38c3a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Models\**" />
    <Content Remove="Models\**" />
    <EmbeddedResource Remove="Models\**" />
    <None Remove="Models\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.IdentityModel.Tokens" />
	<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
	  <PackageReference Include="Swashbuckle.AspNetCore" />
	  <PackageReference Include="Swashbuckle.AspNetCore.Swagger" />
	  <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" />
	  <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EduSense.Infrastructure\EduSense.Infrastructure.csproj" />
    <ProjectReference Include="..\EduSense.BLL\EduSense.BLL.csproj" />
    <ProjectReference Include="..\EduSense.DAL\EduSense.DAL.csproj" />
    <ProjectReference Include="..\EduSense.Shared\EduSense.Shared.csproj" />
  </ItemGroup>

</Project>
