<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\EduSense.API\EduSense.API.csproj" />
		<ProjectReference Include="..\EduSense.BLL\EduSense.BLL.csproj" />
		<ProjectReference Include="..\EduSense.DAL\EduSense.DAL.csproj" />
		<ProjectReference Include="..\EduSense.UI\EduSense.UI.csproj" />
	</ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" >
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.runner.visualstudio" >
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="bunit" />
		<PackageReference Include="Moq" />
	</ItemGroup>

</Project>